
    "#McCulloh Pitt model for AND model\n",
    "import numpy as np\n",
    "\n",
    "def McNot(x,w,t):\n",
    "    net = np.dot(x,w)\n",
    "    if net>t:\n",
    "        output = 1\n",
    "    else:\n",
    "        output = 0\n",
    "    return output\n",
    "\n",
    "x0 = np.array([0,1])\n",
    "x1 = np.array([1,1])\n",
    "w = np.array([1,-1])\n",
    "\n",
    "t = 0\n",
    "ans1 = McNot(x0,w,t)\n",
    "print (x0, \"value\", ans1)\n",
    "ans2 = McNot(x1,w,t)\n",
    "print (x1, \"value\", ans2)"
   
